modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="ore_mod"
version="1.0.0"
displayName="Ore Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="AJaxx, MCreator"

[[dependencies.ore_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



